### ISSUE TITLE
event.js - throw er; unhandled error event (crashes alexa-app-server)

### ISSUE THREAD

**Issue by jradwan** [jradwan/alexa_tivo_control#1]
If commands are queued up to be sent to the TiVo and the TiVo is not responding for some reason (i.e., connection closed), the alexa-app-server will crash:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:276:12)
    at sendNextCommand (/usr/src/alexa-app-server/apps/alexa_tivo_control/app.js:819:30)
    at wrapper (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

This seems to happen mostly after launching a provider (i.e., YouTube). The TiVo stops responding to voice commands, so they queue up and then timeout and crash. I thought this used to work so I'm not sure what change I did that caused this to break. Need to investigate.

**Comment by jradwan** [comment]
One way to easily replicate this, it seems, is to try sending commands to the TiVo during playback of recorded video.

**Comment by jradwan** [comment]
This was actually being caused by commands being queued up and never sent while the TiVo was playing back a recording, see issue #3.
